core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('base/', views.kbase, name='kbase')
]

mobikb_v1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('operators/', include('providers.urls')),
    path('shiftlog/', include('shiftlog.urls')),
    path('assistant', include('assistant.urls'))
]

providers/urls.py
from django.urls import path
from . import views


app_name = 'providers'


# temp = 'providers:operators'

urlpatterns = [
    path('', views.opeartors, name='operators'),
    path('<int:pk>', views.operator_detail, name = 'operator_detail'),
    path('get-country-data/<int:operator_id>/<str:country_code>/', views.get_country_data, name='get_country_data'),
]

providers/models.py
from django.db import models
from django_countries.fields import CountryField


class Operator(models.Model):
    operator_name = models.CharField(max_length=64)
    
    contact_list = models.TextField(max_length=500, default='n/a')
    contact_notes = models.CharField(max_length=1000, default='n/a')
    
    phone_no = models.CharField(max_length=255, default='n/a')
    call_min = models.CharField(max_length=500, default='n/a')
    topup_eligibility = models.CharField(max_length=500) # link to topup
    
    provider_name = models.CharField(max_length=124)
    apn = models.CharField(max_length=64)
    iccid = models.CharField(max_length=100)

    check_usage = models.CharField(max_length=200, default='n/a')
    esim_status = models.CharField(max_length=255, default='n/a')
    ip_breakout = models.CharField(max_length=100, default='n/a') # needs to be added
    

    activation = models.CharField(max_length=1000, default='n/a')
    pkg_change = models.CharField(max_length=1000, default='n/a')
    esim_replacement = models.CharField(max_length=1000, default='n/a')
    
    cancellation = models.CharField(max_length=1000, default='n/a')
    cancel_if_activated = models.CharField(max_length=1000, default='n/a')
    admin_refund_method = models.CharField(max_length=1000, default='n/a')
    second_tier_notes = models.CharField(max_length=1000, default='n/a')


    def __str__(self):
        return f"{self.operator_name}"


class Network(models.Model):
    network_name = models.CharField(max_length=24)
    
    def __str__(self):
        return self.network_name


class CountryData(models.Model):
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE)
    country = CountryField()
    # change the kyc_policy to country restrictions
    kyc_policy = models.CharField(max_length=1000)
    networks = models.ManyToManyField(Network) 
    
    def __str__(self):
        return f"{self.operator} in {self.country}"

providers/forms.py
from django import forms
from .models import Operator, Network, CountryData, CountryField

class OperatorForm(forms.ModelForm):
    class Meta:
        model = Operator
        fields = '__all__'
        

providers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Operator, CountryData
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import OperatorForm

@login_required
def opeartors(request):
    return render(request, 'opeartors.html', {'Operators': Operator.objects.all()})

@login_required
def operator_detail(request, pk):
    operator_instance = get_object_or_404(Operator, id=pk)
    country_data = CountryData.objects.filter(operator=operator_instance)
    
    return render(request, 'operator_detail.html', {
        'operator': operator_instance,
        'country_data': country_data
    })

def get_country_data(request, operator_id, country_code):
    try:
        # Fetch the relevant CountryData instance based on operator and country
        country_data = CountryData.objects.get(operator_id=operator_id, country=country_code)
        
        # Prepare the data to return, including multiple networks
        data = {
            'kyc_policy': country_data.kyc_policy,
            'networks': [network.network_name for network in country_data.networks.all()]
        }
        return JsonResponse(data)
    except CountryData.DoesNotExist:
        return JsonResponse({}, status=404)
    
    
# def createOperatorView(request):
#     form = OperatorForm
#     if request.method == "POST":
#         form = OperatorForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect("providers:operators")

providers/templates/opeartors.html
{% extends 'base.html' %} {% block content %}
<br />
<h1>Operators</h1>
<br />
<div class="hstack gap-3">
  {% for operator in Operators %}

  <div class="p-2">
    <button type="button" class="btn btn-secondary btn-lg">
      <a
        class="text-decoration-none link-light"
        href="{% url 'providers:operator_detail' operator.id %}"
        >{{ operator.operator_name }}</a
      >
    </button>
  </div>
  {% endfor %}
</div>
{% endblock content %}

providers/templates/operator_detail.html
{% extends 'base.html' %} {% block content %}

<h1 class="text-center my-4">
  <i class="bi bi-gear-fill"></i> Operator Details
  <strong>({{ operator.operator_name }})</strong>
</h1>

<!-- Operator Info Section -->
<div class="container-fluid">
  <div class="row g-2 p-2">
    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-messenger"></i> <strong>Contact</strong>
        </h6>
        <p class="card-text">{{ operator.contact_list }}</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-info-circle"></i> <strong>Contact Notes</strong>
        </h6>
        <p class="card-text">{{ operator.contact_notes }}</p>
      </div>
    </div>

    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-building"></i> <strong>Provider</strong>
        </h6>
        <span class="badge text-bg-info">
          <p class="card-text">{{ operator.provider_name }}</p></span
        >
      </div>
    </div>

    <div class="col-md-1">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-broadcast"></i>
          <strong>IP</strong>
        </h6>

        <span class="badge text-bg-info"
          ><p class="card-text">{{ operator.ip_breakout }}</p></span
        >
      </div>
    </div>

    <div class="col-md-1">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-phone"></i> <strong>eSIM no</strong>
        </h6>
        <p class="card-text">{{ operator.phone_no }}</p>
      </div>
    </div>

    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-currency-exchange"></i> <strong>Minutes</strong>
        </h6>
        <p class="card-text">{{ operator.call_min }}</p>
      </div>
    </div>

    <div class="col-md-1">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-arrow-clockwise"></i>
          <strong>Top-Up</strong>
        </h6>
        {% if operator.topup_eligibility|slice:":4" == "http" %}
        <a
          href="{{ operator.topup_eligibility }}"
          target="_blank"
          class="btn btn-primary btn-sm text-white"
        >
          <i class="bi bi-arrow-right-circle"></i> {{operator.operator_name}}
        </a>
        {% else %}
        <span>Not available</span>
        {% endif %}
      </div>
    </div>
  </div>

  <!-- second row -->
  <div class="row g-2 p-2">
    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-apple"></i> <strong>APN</strong>
        </h6>
        <p class="card-text">{{ operator.apn }}</p>
      </div>
    </div>

    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-camera"></i> <strong>eSIM Status</strong>
        </h6>
        <p class="card-text">{{ operator.esim_status }}</p>
      </div>
    </div>

    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-credit-card"></i> <strong>ICCID</strong>
        </h6>
        <p class="card-text">{{ operator.iccid }}</p>
      </div>
    </div>

    <div class="col-md-2">
      <div class="card text-dark bg-light p-2 h-100 shadow-lg rounded">
        <h6 class="card-title">
          <i class="bi bi-file-earmark-check"></i> <strong>Check Usage</strong>
        </h6>

        <p class="card-text">{{ operator.check_usage }}</p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-file-earmark-check"></i>
          <strong>Activation</strong>
        </h6>

        <p class="card-text">{{ operator.activation }}</p>
      </div>
    </div>
  </div>
</div>

<br />

<!-- Policy/Process Section -->
<div class="container-fluid">
  <div class="row g-2 p-2">
    <div class="col-md-3">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-x-circle"></i> <strong>Refund & Cancellation</strong>
        </h6>
        <p class="card-text">{{ operator.cancellation }}</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-circle-fill"></i>
          <strong>Refund If Activated with not usage</strong>
        </h6>
        <p class="card-text">{{ operator.cancel_if_activated }}</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-window"></i>
          <strong>Admin Refund Method</strong>
        </h6>
        <p class="card-text">{{ operator.admin_refund_method }}</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-arrows-move"></i>
          <strong
            >Package Change
            <span class="badge text-bg-warning">(2nd Tier)</span>
          </strong>
        </h6>
        <p class="card-text">{{ operator.pkg_change }}</p>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-arrow-repeat"></i>
          <strong>eSIM Replacement</strong>
        </h6>
        <p class="card-text">{{ operator.esim_replacement }}</p>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card p-3 bg-light text-dark h-100 shadow-lg rounded mb-4">
        <h6 class="card-title">
          <i class="bi bi-person-up"></i>
          <strong
            >Second Tier Notes
            <span class="badge text-bg-warning">(2nd Tier)</span></strong
          >
        </h6>
        <p class="card-text">{{ operator.second_tier_notes }}</p>
      </div>
    </div>
  </div>
</div>

<!-- Country Selection and Data Display Section -->
<div class="container my-4">
  <div class="row g-2 p-2">
    <div class="col-md-4">
      <div class="sticky-top">
        <div class="card bg-secondary text-white shadow-lg rounded mb-4">
          <div class="card-body p-3">
            <h5><i class="bi bi-globe"></i> Select a Country</h5>
            <select id="countrySelect" class="form-select">
              <option value="">Select a country</option>
              {% for country in country_data %}
              <option value="{{ country.country }}">
                {{ country.country.name }}
              </option>
              {% endfor %}
            </select>
            <br />
            <ul>
              <li>
                <i class="bi bi-geo-alt"></i> Networks & Country Restrictions
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div
        class="card bg-light p-3 shadow-lg rounded mb-4"
        id="countryDetails"
        style="display: none"
      >
        <h5>Country Details</h5>
        <div id="detailsContent"></div>
      </div>
    </div>
  </div>
</div>

<script>
  document
    .getElementById("countrySelect")
    .addEventListener("change", function () {
      const countryCode = this.value;
      const operatorId = "{{ operator.id }}";

      if (countryCode) {
        fetch(`get-country-data/${operatorId}/${countryCode}/`)
          .then((response) => response.json())
          .then((data) => {
            if (data) {
              let networkBadges = "";
              data.networks.forEach((network) => {
                networkBadges += `<span class="badge bg-info text-dark me-1">${network}</span>`;
              });

              document.getElementById("detailsContent").innerHTML = `
                <h6>Networks:</h6>
                <p>${networkBadges}</p>
                <p><strong>Country Restrictions & KYC:</strong> <span class="badge bg-danger text-light me-1">${data.kyc_policy}</span></p>
              `;
              document.getElementById("countryDetails").style.display = "block";
            }
          });
      } else {
        document.getElementById("countryDetails").style.display = "none";
      }
    });
</script>

{% endblock content %}